name: Build Release Binaries

on:
  push:
    tags:
      - 'v*' # Запускается при пуше тегов, начинающихся с 'v' (v1.0.0, v1.0.1-beta и т.д.)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Указываем целевые операционные системы и архитектуры
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: local-video-server-linux-amd64
          - os: macos-latest
            artifact_name: local-video-server-darwin-amd64
          - os: windows-latest
            artifact_name: local-video-server-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -o ${{ matrix.artifact_name }} ./cmd  # Уточните путь к main пакету, например ./cmd/server
        shell: bash

      # Загрузка собранного артефакта в список результатов выполнения workflow
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
